version: "3"
services:
  nginx:
    image: nginx:latest
    volumes:
      - ./app:/app
      - ./site.conf:/etc/nginx/conf.d/default.conf
    networks:
      codeigniter_net:
    ports:
      - "8000:8000"
    restart: always

  php:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    networks:
      codeigniter_net:

networks:
  codeigniter_net:
